services:
  frontend:
    build: frontend/.
    container_name: frontend
    ports:
      - "443:443"
    volumes:
      - certs:/certs
    networks:
      - transcendence

  backend:
    build: backend/.
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - certs:/certs
    networks:
      - transcendence

  database:
    build: database/.
    container_name: database
    volumes:
      - database:/database
    networks:
      - transcendence

volumes:
  certs:
  database:

networks:
  transcendence:
    name: transcendence
    driver: bridge
