services:
  frontend:
    build: frontend/.
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "443:443"
    networks:
      - transcendence
    restart:
      condition: service-healthy
  backend:
    build: backend/.
    container_name: backend
    network:
      - transcendence
networks:
  inception:
    name: transcendence
    driver: bridge

