services:
  frontend:
    build: frontend/.
    container_name: frontend
    ports:
      - "443:443"
    volumes:
      - certs:/certs
    env_file:
      - .env
    networks:
      - transcendence

  backend:
    build: backend/.
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - certs:/certs
      - database:/database
    env_file:
      - .env
    networks:
      - transcendence

  database:
    build: database/.
    container_name: database
    ports:
      - "3451:3451"
    volumes:
      - certs:/certs
      - database:/database
    env_file:
      - .env
    networks:
      - transcendence

volumes:
  certs:
  database:

networks:
  transcendence:
    name: transcendence
    driver: bridge
