services:
  frontend:
    build: frontend/.
    container_name: frontend
    ports:
      - "443:443"
    volumes:
      - certs:/certs
    env_file:
      - .env
    networks:
      - transcendence

  backend:
    build: backend/.
    container_name: backend
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
      - "3006:3006"
      - "3007:3007"
      - "3008:3008"
      - "3009:3009"
      - "3010:3010"
      - "3011:3011"
      - "3012:3012"
      - "3013:3013"
      - "3014:3014"
      - "3015:3015"
      - "3016:3016"
      - "3017:3017"
      - "3018:3018"
      - "3019:3019"
      - "3020:3020"
      - "3021:3021"
      - "3022:3022"
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3026:3026"
      - "3027:3027"
      - "3028:3028"
      - "3029:3029"
      - "3030:3030"
      - "3031:3031"
      - "3032:3032"
      - "3033:3033"
      - "3034:3034"
      - "3035:3035"
      - "3036:3036"
      - "3037:3037"
      - "3038:3038"
      - "3039:3039"
      - "3040:3040"
      - "3041:3041"
      - "3042:3042"
      - "3043:3043"
      - "3044:3044"
      - "3045:3045"
      - "3046:3046"
      - "3047:3047"
      - "3048:3048"
      - "3049:3049"
      - "3050:3050"
      # - "3451:3451"
      - "4000:4000"
    volumes:
      - certs:/certs
      - database:/database
    env_file:
      - .env
    networks:
      - transcendence

  database:
    build: database/.
    container_name: database
    ports:
      - "3451:3451"
      - "3453:3453"
    volumes:
      - certs:/certs
      - database:/database
    env_file:
      - .env
    networks:
      - transcendence

volumes:
  certs:
  database:

networks:
  transcendence:
    name: transcendence
    driver: bridge
