"use strict";
const editbtn = document.getElementById('edit-btn');
const statsbtn = document.getElementById('stats-btn');
const statsform = document.getElementById('stats-form');
const editprofilform = document.getElementById('edit-profil-form');
let editbtnisactive = false;
let statsbtnisactive = true;
editbtn.addEventListener('click', () => {
    if (editbtnisactive)
        return;
    editbtnisactive = true;
    statsbtnisactive = false;
    statsbtn.classList.add('bg-gray-200');
    statsbtn.classList.remove('bg-blue-600');
    editbtn.classList.remove('bg-gray-200');
    editbtn.classList.add('bg-blue-500');
    editbtn.classList.add('text-white');
    editbtn.classList.remove('text-gray-700');
    statsbtn.classList.remove('text-white');
    statsbtn.classList.add('text-gray-700');
    statsbtn.classList.remove('hover:bg-blue-700');
    statsbtn.classList.add('hover:bg-gray-300');
    editbtn.classList.remove('hover:bg-gray-300');
    editbtn.classList.add('hover:bg-blue-700');
    statsform.classList.add('hidden');
    editprofilform.classList.remove('hidden');
    editpasswordform.classList.add('hidden');
    editpasswordbtn.classList.remove('hidden');
});
statsbtn.addEventListener('click', () => {
    if (statsbtnisactive)
        return;
    editbtnisactive = false;
    statsbtnisactive = true;
    statsbtn.classList.remove('bg-gray-200');
    statsbtn.classList.add('bg-blue-600');
    editbtn.classList.add('bg-gray-200');
    editbtn.classList.remove('bg-blue-500');
    statsbtn.classList.add('text-white');
    statsbtn.classList.remove('text-gray-700');
    editbtn.classList.remove('text-white');
    editbtn.classList.add('text-gray-700');
    editbtn.classList.remove('hover:bg-blue-700');
    editbtn.classList.add('hover:bg-gray-300');
    statsbtn.classList.remove('hover:bg-gray-300');
    statsbtn.classList.add('hover:bg-blue-700');
    statsform.classList.remove('hidden');
    editprofilform.classList.add('hidden');
    editpasswordform.classList.add('hidden');
    editpasswordbtn.classList.remove('hidden');
    editusernameinput.value = "";
    editemailinput.value = "";
    editcurrentpasswordinput.value = "";
    editnewpasswordinput.value = "";
    editconfirmnewpasswordinput.value = "";
});
const editpasswordbtn = document.getElementById('edit-password-btn');
const editpasswordform = document.getElementById('edit-password-form');
editpasswordbtn.addEventListener('click', () => {
    editprofilform.classList.add('hidden');
    editpasswordform.classList.remove('hidden');
    editpasswordbtn.classList.add('hidden');
});
const unsavebtn = document.getElementById('unsave-btn');
const savebtn = document.getElementById('save-btn');
const editusernameinput = document.getElementById('edit-username-input');
const editemailinput = document.getElementById('edit-email-input');
const editcurrentpasswordinput = document.getElementById('edit-currentpassword-input');
const editnewpasswordinput = document.getElementById('edit-newpassword-input');
const editconfirmnewpasswordinput = document.getElementById('edit-confirmpassword-input');
const unsavebtneditpassword = document.getElementById('unsave-btn-edit-password');
unsavebtn.addEventListener('click', () => {
    editusernameinput.value = "";
    editemailinput.value = "";
});
unsavebtneditpassword.addEventListener('click', () => {
    editcurrentpasswordinput.value = "";
    editnewpasswordinput.value = "";
    editconfirmnewpasswordinput.value = "";
    editprofilform.classList.remove('hidden');
    editpasswordform.classList.add('hidden');
    editpasswordbtn.classList.remove('hidden');
});
